### PR TITLE
Add Into<u32> for Pid

### LINKED ISSUE #2: Get the PID as u32
Maybe implement a function that allows to get a PID as u32 for example if someone want to continue using it as a number.

### PR DESCRIPTION
**Pull request by JojiiOfficial**
Fixes #2

### CODE REVIEW

**Comment by jabedude** [comment]
Thanks for the PR! I think it would be better to instead implement `From<Pid> for u32` here, since it [automatically provides Into<u32>](https://doc.rust-lang.org/std/convert/trait.From.html).

**Comment by JojiiOfficial** [comment]
Makes sense. Here the changes :)

**Comment by jabedude** [comment]
Great, thanks! Can you squash your two commits into one please?

**Comment by jabedude** [comment]
Thank you :)

**Pull request merged**
